### ISSUE TITLE
 sync video playback with the original FPS don't work

### ISSUE THREAD

**Issue by mass44** [cedricfung/MediaCodecDemo#2]

**Comment by cedricfung** [comment]
What video? This should work under most common situations.

**Comment by mass44** [comment]
3gp and MP4 , the video is playing very fast.

**Comment by cedricfung** [comment]
Could you please send me a short video sample? cedric@vec.io

**Comment by mass44** [comment]
Just tested on 4.4 and it work perfectly but the issue seems to be only on 4.1 with both 3gp and mp4 file. I can't send you a video with this device ( not able to record )
